/*! Drawform v0.1-beta (20101006) <http://burzak.com/proj/drawform/> 
    released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
(function(){function f(){this.rules=[];this.ruleIndex=[];if(document.createStyleSheet)this.sheet=document.createStyleSheet();else{this.styleElement=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(this.styleElement);this.sheet=this.styleElement.styleSheet?this.styleElement.styleSheet:this.styleElement.sheet}}if(!window._CSSStyleSheet){window._CSSStyleSheet=f;f.prototype.addRule=function(c,a){var b;if(this.sheet)if(this.sheet.addRule){a=a.replace(/^\{?([^\}])/,"$1");
var d=this.sheet.rules.length;this.sheet.addRule(c,a);b=this.sheet.rules[d];this.ruleIndex[c]=d;if(this.rules.length==0)this.rules=this.sheet.rules}else if(this.sheet.insertRule){/^\{[^\}]*\}$/.test(a)||(a="{"+a+"}");d=this.sheet.cssRules.length;this.sheet.insertRule(c+" "+a,d);b=this.sheet.cssRules[d];this.ruleIndex[c]=d;if(this.rules.length==0)this.rules=this.sheet.cssRules}else alert("Cannot create rule");else{a=a.replace(/^\{?([^\}])/,"$1");if(!this.ruleIndex[c])this.ruleIndex[c]=this.rules.length;
this.rules[this.ruleIndex[c]]=a;d="";for(var e in this.ruleIndex)d=e+" {"+this.rules[this.ruleIndex[e]]+"}";this.styleElement.innerHTML=d}return b};f.prototype.changeRule=function(c,a,b){var d=this.ruleIndex[c];typeof d=="undefined"&&this.addRule(c,a+":"+b);if(this.sheet)if(this.rules[d].style){for(c=/^([^-]*)-([a-z])(.*)$/.exec(a);c;){a=c[1]+c[2].toUpperCase()+c[3];c=/^([^-]*)-([a-z])(.*)$/.exec(a)}this.rules[d].style[a]=b}else{if(this.sheet.insertRule){var e=this.rules[d];if(e){e=e.cssText;g=RegExp("^[^\\{]*(\\{.*"+
a+"\\s*\\:\\s*)([^};]*)([^}]*})");if(g=g.exec(e)){if(g[4]!=b){e=g[1]+b+g[3];this.sheet.deleteRule(d);this.sheet.insertRule(c+" "+e,d)}}else{g=/\{([^}]*)}/;g=g.exec(e);e="{ "+g[1]+"; "+a+": "+b+" }";this.sheet.deleteRule(d);this.sheet.insertRule(c+" "+e,d)}}}}else{if(e=this.rules[d]){var g=RegExp("^(.*"+a+"\\s*:\\s*)([^;]*)(.*)$");if(g=g.exec(e)){if(g[4]!=b)this.rules[d]=g[1]+b+g[3]}else this.rules[d]=e+"; "+a+": "+b+";";e="";for(var h in this.ruleIndex)e=h+" {"+this.rules[this.ruleIndex[h]]+"}";this.styleElement.innerHTML=
e}for(h in this.ruleIndex);}};f.prototype.getRuleProperty=function(c,a){var b=this.ruleIndex[c];if(typeof b!="undefined")if(this.sheet)if(this.rules[b].style){for(var d=/^([^-]*)-([a-z])(.*)$/.exec(a);d;){a=d[1]+d[2].toUpperCase()+d[3];d=/^([^-]*)-([a-z])(.*)$/.exec(a)}return this.rules[b].style[a]}else{if(this.sheet.insertRule)if(b=this.rules[b]){b=b.cssText;d=RegExp("^.*"+a+"\\s*\\:\\s*([^};]*)");if(b=d.exec(b))return b[1]}}else if(b=this.rules[b]){d=RegExp("^.*"+a+"s*:s*([^;]*)");if(b=d.exec(b))return b[1]}}}})();
(function(){function f(e){if(c.browser.isIE&&c.browser.ie<8)throw Error("Internet Explorer "+c.browser.ie+" is not supported at this moment");w3c(e);var g=e.getAttribute("id")||"drawform"+d,h=e.getAttribute("width")||a,j=e.getAttribute("height")||b;if(e.__defineSetter__){e.__defineSetter__("width",function(n){this.setAttribute("width",n)});e.__defineSetter__("height",function(n){this.setAttribute("height",n)});e.__defineGetter__("width",function(){return Number(this.getAttribute("width"))});e.__defineGetter__("height",
function(){return Number(this.getAttribute("height"))});e.__defineSetter__("src",function(n){this.setAttribute("src",n)});e.__defineGetter__("src",function(){return this.getAttribute("src")});e.__defineSetter__("name",function(n){n&&this.setAttribute("name",n)});e.__defineGetter__("name",function(){return this.getAttribute("name")})}var k=function(){if(i!=h||l!=j){e.__resize(i,l);h=Number(i);j=Number(l)}},i=h,l=j,m;c.propertyChangeListener(e,"width",function(n){i=Number(n.newValue);clearTimeout(m);
m=setTimeout(k,20)});c.propertyChangeListener(e,"height",function(n){l=Number(n.newValue);clearTimeout(m);m=setTimeout(k,30)});c.propertyChangeListener(e,"name",function(n){var o=e.getContext("default");o.name=n.newValue;setTimeout(o.aT,1)});c.propertyChangeListener(e,"src",function(){e.getContext("default").aG.oncanvasresize()});c.drawform.App["new"](e,g,h,j);d+=1}var c=$Import({},"browser","buz.fxcanvas.config","buz.drawform","buz.util.*"),a=300,b=150,d=0;c.browser.isIE&&document.createElement("drawform");
document.__drawform__native_createElement=document.createElement;document.createElement=function(e){e=this.__drawform__native_createElement(e);e.tagName=="DRAWFORM"&&f(e);return e};(new _CSSStyleSheet).addRule("drawform",["display:inline-block;overflow:hidden","width:"+a+"px","height:"+b+"px",""].join(";"));addDOMLoadEvent(function(){var e=HTMLCanvasElement.prototype;e.__native__loadImage=e.loadImage;e.loadImage=function(){for(var j,k,i=0;i<arguments.length;i++){j=arguments[i];k=null;if(typeof j==
"object")k=j.src;else if(typeof j=="string")k=j;if(k)if(k.indexOf(location.protocol+"//"+location.hostname)!==0)if(/^https?:\/\//.test(k))arguments[i]=c.config.imageProxy+"?url="+k}e.__native__loadImage.apply(this,arguments)};for(var g=document.getElementsByTagName("drawform"),h=0;h<g.length;h++)f(g[h])},false)})();
$Unit("","",function(){$Package("buz.drawform.pens",function(){this.addClass(0,$buildClass("Standard",[],function(){this.__add__(2,"id","standard");this.__add__(0,"shape","circle");this.__add__(0,"daubSize",20);this.__add__(0,"daubStep",5);this.__add__(0,"__new__",function(f,c){if(c){if(c.shape)f.shape=c.shape;if(c.daubSize)f.daubSize=c.daubSize;if(c.daubStep)f.daubStep=c.daubStep}});this.__add__(0,"D",function(f,c,a,b){var d=f.daubSize/2;if(f.shape=="circle")c.arc(a,b,d,0,360*Math.PI/180,false);
else f.shape=="rect"&&c.rect(a-d,b-d,f.daubSize,f.daubSize)});this.__add__(0,"bone",function(f,c,a,b){f.D(c,a,b)})}))})});
$Unit("","",function(){$Package("buz.drawform.tools",function(){this.addClass(0,$buildClass("Dummy",[],function(){this.__add__(2,"id","dummy");this.__add__(0,"a",function(){});this.__add__(0,"b",function(){});this.__add__(0,"c",function(){});this.__add__(0,"d",function(){});this.__add__(0,"e",function(){});this.__add__(0,"f",function(){});this.__add__(0,"g",function(){});this.__add__(0,"h",function(){});this.__add__(0,"i",function(){});this.__add__(0,"j",function(){});this.__add__(0,"k",function(){});
this.__add__(0,"l",function(){});this.__add__(0,"aJ",function(){});this.__add__(0,"n",function(){})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Move",[c.Dummy],function(){this.__add__(2,"id","move");this.__add__(0,"__new__",function(a){a.E=a.parent;a.touch=false;a.flowArea=null;a.F=null;a.G=false});this.__add__(0,"c",function(a,b,d){if(a.E.flowArea)if(a.E.flowArea.isPointWithin(b,d))a.flowArea=a.E.flowArea;else return;if(a.flowArea){a.touch=true;a.H=f.geom.Point["new"](b,d);a.F||a.E.o.aV.invoke("getImageData",a.flowArea,function(e){a.E.o.clear();
a.F=e;a.F.__useCache=true})}});this.__add__(0,"d",function(a){a.G=a.touch=false});this.__add__(0,"e",function(a,b,d){if(!a.G)if(a.touch&&a.F){var e=a.H.vectorTo(b,d),g=a.flowArea;if(e.x+g.x<0)g.x=0;else if(e.x+g.x+g.width>a.E.width)g.x=a.E.width-g.width;else g.x+=e.x;if(e.y+g.y<0)g.y=0;else if(e.y+g.y+g.height>a.E.height)g.y=a.E.height-g.height;else g.y+=e.y;a.G=true;a.E.p.aV.clear().invoke("putImageData",a.F,g.x,g.y,function(){a.G=false});a.H.x=b;a.H.y=d}});this.__add__(0,"aJ",function(a){if(a.F){a.F.__destroy();
a.F=null;a.E.p.aV.clear()}});this.__add__(0,"n",function(a){if(a.F){var b=a.E.flowArea;b?a.E.o.aV.invoke("putImageData",a.F,b.x,b.y,a.aJ):a.aJ()}})}))})});
$Unit("","",function(){$Package("buz.drawform.tools",function(f){this.addClass(0,$buildClass("Pencil",[f.Dummy],function(){this.__add__(2,"id","pencil");this.__add__(0,"__new__",function(c){c.I=c.J=0;c.touch=false;c.E=c.parent;c.K=c.E.r.aV;c.L=c.E.o.aV});this.__add__(0,"c",function(c,a,b){c.touch=true;c.I=a;c.J=b;c.path=c.K.createPath();c.path.moveTo(a,b)});this.__add__(0,"d",function(c){c.touch=false;c.k(c.L);c.aJ();c.path=null});this.__add__(0,"e",function(c,a,b){if(c.touch){c.K.setStrokeStyle(c.E.strokeStyle).setLineWidth(c.E.lineWidth).setLineJoin("round").beginPath().moveTo(c.I,
c.J).lineTo(a,b).stroke();c.I=a;c.J=b;c.path.lineTo(a,b)}});this.__add__(0,"k",function(c,a){c.path&&a.setStrokeStyle(c.E.strokeStyle).setLineWidth(c.E.lineWidth).setLineJoin("round").beginPath().appendPath(c.path).stroke()});this.__add__(0,"aJ",function(c){c.K.clear()});this.__add__(0,"n",function(c){c.k(c.L)})}))})});
$Unit("","",function(){$Package("buz.drawform.tools",function(f){this.addClass(0,$buildClass("Path",[f.Dummy],function(){this.__add__(2,"id","path");this.__add__(0,"__new__",function(c){c.M=c.N=0;c.I=c.J=0;c.x=c.y=0;c.O=false;c.E=c.parent;c.K=c.E.r.aV;c.L=c.E.o.aV;c.path=c.K.createPath()});this.__add__(0,"c",function(c,a,b){if(c.O)c.path.lineTo(a,b);else{c.path=c.K.createPath();c.path.moveTo(a,b);c.O=true;c.M=a;c.N=b}c.I=a;c.J=b});this.__add__(0,"g",function(c){c.O=false;c.aJ();c.P();c.path=null});
this.__add__(0,"e",function(c,a,b){if(c.O){c.x=a;c.y=b;c.E.r.aY()}});this.__add__(0,"P",function(c){var a=c.E.o;a.aV.save();a.aa();c.k(c.L);a.aV.restore()});this.__add__(0,"k",function(c,a){c.path&&a.setStrokeStyle(c.E.strokeStyle).setLineWidth(c.E.lineWidth).setLineJoin("round").beginPath().appendPath(c.path).stroke();c.l(c.K)});this.__add__(0,"l",function(c,a){c.O&&a.setStrokeStyle("white").setLineWidth(3).beginPath().moveTo(c.I,c.J).lineTo(c.x,c.y).stroke().setStrokeStyle("black").setLineWidth(1).setLineJoin("round").beginPath().moveTo(c.I,
c.J).lineTo(c.x,c.y).stroke().setFillStyle("white").fillRect(c.M-2,c.N-2,5,5).setFillStyle("black").fillRect(c.M-1,c.N-1,3,3)});this.__add__(0,"aJ",function(c){c.K.clear()});this.__add__(0,"n",function(c){c.k(c.L)})}))})});
$Unit("","",function(f){$Import(f,"geom","buz.drawform.pens");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Pen",[c.Dummy],function(){this.__add__(2,"id","pen");this.__add__(0,"H");this.__add__(2,"pens",{});this.__add__(0,"compositeOperation","normal");this.__add__(0,"__new__",function(a,b,d,e){a.I=a.J=0;a.Q=a.R=0;a.touch=false;a.E=a.parent;a.K=a.E.r.aV;a.L=a.E.o.aV;b||(b="standard");if(e)a.compositeOperation=e;a.S(b,d);a.E.aK(null);a.fillStyle=a.E.fillStyle});this.__add__(0,
"S",function(a,b,d){b=a.__class__.pens[b.toLowerCase()];a.pen=b["new"](d)});this.__add__(2,"regPen",function(a){this.pens[a.id.toLowerCase()]=a});this.__add__(2,"__init__",function(){this.regPen(f.pens.Standard)});this.__add__(0,"c",function(a,b,d){a.touch=true;a.H=f.geom.Point["new"](b,d);a.T=[[b,d]];a.U=[a.T];a.Q=b;a.R=d;a.l(a.K)});this.__add__(0,"d",function(a){a.k(a.L);a.T=a.U=null;a.touch=false});this.__add__(0,"e",function(a,b,d){a.K.clear();a.E.r.aZ();if(a.touch){var e=a.H.vectorTo(b,d);e=
Math.sqrt(e.x*e.x+e.y*e.y);var g=a.H.x,h=a.H.y,j=g,k=h,i;i=a.pen.daubStep;if(e>=i){var l=Math.atan2(b-g,d-h);g=i;h=Math.sin(l);l=Math.cos(l);h=i*h;for(i=i*l;g<e;){j+=h;k+=i;a.T.push([j,k]);g+=Math.sqrt(h*h+i*i);if(!g)break}a.H.x=b;a.H.y=d}}a.Q=b;a.R=d;a.l(a.K)});this.__add__(0,"k",function(a){if(a.touch&&a.T){for(var b=0;b<a.U.length;b++){a.T=a.U[b];a.V(a.L)}a.T=[];a.U=[a.T]}});this.__add__(0,"l",function(a,b){a.touch&&a.V(b);b.setStrokeStyle("white").setLineWidth(3).beginPath();a.pen.bone(b,a.Q,
a.R);b.stroke().setStrokeStyle("black").setLineWidth(1).beginPath();a.pen.bone(b,a.Q,a.R);b.stroke()});this.__add__(0,"V",function(a,b){if(a.touch&&a.T){var d=b.globalCompositeOperation;b.setFillStyle(a.fillStyle);b.setGlobalCompositeOperation(a.compositeOperation=="light"?"lighter":a.compositeOperation=="normal"?"source-over":"unknown");for(var e=0;e<a.T.length;e++){b.beginPath();a.pen.D(b,a.T[e][0],a.T[e][1]);b.fill()}b.globalCompositeOperation=d}})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Rect",[c.Dummy],function(){this.__add__(2,"id","rectangle");this.__add__(0,"__new__",function(a){a.touch=false;a.E=a.parent;a.K=a.E.r.aV;a.L=a.E.o.aV;a.I=a.J=a.width=a.height=0});this.__add__(0,"c",function(a,b,d){a.touch=true;a.H=f.geom.Point["new"](b,d)});this.__add__(0,"d",function(a){a.touch=false;a.E.r.clear();a.k(a.L);a.I=a.J=a.width=a.height=0});this.__add__(0,"e",function(a,b,d){if(a.touch){var e=
a.H.vectorTo(b,d),g;if(e.x<0&&e.y<0){b=a.H.x+e.x;d=a.H.y+e.y;g=-e.x;e=-e.y}else if(e.x<0){b=a.H.x+e.x;d=a.H.y;g=-e.x;e=e.y}else if(e.y<0){b=a.H.x;d=a.H.y+e.y;g=e.x;e=-e.y}else{b=a.H.x;d=a.H.y;g=e.x;e=e.y}a.I=b;a.J=d;a.width=g;a.height=e;a.E.r.aY()}});this.__add__(0,"k",function(a,b){a.width&&a.height&&b.setFillStyle(a.E.fillStyle).setStrokeStyle(a.E.strokeStyle).setLineWidth(a.E.lineWidth).fillRect(a.I,a.J,a.width,a.height).strokeRect(a.I,a.J,a.width,a.height)});this.__add__(0,"l",function(a,b){a.width&&
a.height&&b.setStrokeStyle("white").setLineWidth(3).strokeRect(a.I,a.J,a.width,a.height).setStrokeStyle("black").setLineWidth(1).strokeRect(a.I,a.J,a.width,a.height)})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Ellipse",[c.Dummy],function(){this.__add__(2,"id","ellipse");this.__add__(0,"__new__",function(a){a.I=a.J=a.W=a.X=0;a.touch=false;a.E=a.parent;a.K=a.E.r.aV;a.L=a.E.o.aV});this.__add__(0,"c",function(a,b,d){a.touch=true;a.H=f.geom.Point["new"](b,d)});this.__add__(0,"d",function(a){a.touch=false;a.E.r.clear();a.k(a.L);a.I=a.J=a.W=a.X=0});this.__add__(0,"e",function(a,b,d){if(a.touch){b=a.H.vectorTo(b,
d);a.I=a.H.x;a.J=a.H.y;a.W=b.x;a.X=b.y;a.E.r.aY()}});this.__add__(1,"k",function(a,b){if(a.W&&a.X){b.setFillStyle(a.E.fillStyle).setStrokeStyle(a.E.strokeStyle).setLineWidth(a.E.lineWidth);a.Y(b);b.fill().stroke()}});this.__add__(1,"l",function(a,b){if(a.W&&a.X){b.setStrokeStyle("white").setLineWidth(3);a.Y(b);b.stroke();b.setStrokeStyle("black").setLineWidth(1);a.Y(b);b.stroke()}});this.__add__(1,"Y",function(a,b){var d=a.I,e=a.J,g=0.5522847498*a.W,h=0.5522847498*a.X;b.beginPath().moveTo(d+a.W,e).bezierCurveTo(d+
a.W,e-h,d+g,e-a.X,d,e-a.X).bezierCurveTo(d-g,e-a.X,d-a.W,e-h,d-a.W,e).bezierCurveTo(d-a.W,e+h,d-g,e+a.X,d,e+a.X).bezierCurveTo(d+g,e+a.X,d+a.W,e+h,d+a.W,e)});this.__add__(0,"aJ",function(){})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Marquee",[c.Rect],function(){this.__add__(2,"id","marquee");this.__add__(0,"__new__",function(a){c.Rect.members.__call__("__new__",a)});this.__add__(0,"c",function(a,b,d){a.I=a.J=a.width=a.height=0;a.touch=true;a.E.flowArea=null;c.Rect.members.__call__("c",a,b,d)});this.__add__(0,"d",function(a){a.touch=false;a.E.r.clear();if(a.width+a.height>=6)a.E.flowArea=f.geom.Rectangle["new"](a.I,
a.J,a.width,a.height);a.width=a.height=0});this.__add__(0,"e",function(a,b,d){c.Rect.members.__call__("e",a,b,d)});this.__add__(1,"k",function(a,b){a.touch&&a.l(b)})}))})});
$Unit("","",function(f){$Import(f,"browser","geom","buz.drawform");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Fill",[c.Dummy],function(){this.__add__(2,"id","fill");this.__add__(0,"contiguous",true);this.__add__(0,"tolerance",30);this.__add__(0,"__new__",function(a,b,d){a.touch=false;a.E=a.parent;a.K=a.E.r.aV;a.L=a.E.o.aV;a.Z=a.E.p.aV;a.aa=true;if(b!=undefined)a.contiguous=!!b;if(d!=undefined)a.tolerance=Number(d)});this.__add__(0,"d",function(a,b,d){if(a.aa){a.ab=a.ac=
null;a.aa=false;a.touch=false;var e=a.E.flowArea||f.geom.Rectangle["new"](0,0,a.E.width,a.E.height),g=f.geom.Point["new"](b,d);if(!(e&&!e.isPointWithin(g))){a.Z.clearRect(0,0,a.E.width,a.E.height);a.L.invoke("getImageData",e,function(h){a.ac=h;a.ab=a.Z.createImageData(e.width,e.height);a.ad(g,e)})}}});this.__add__(1,"ad",function(a,b,d){if(a.ab&&a.ac){a.ae=f.drawform.QueueLinearFloodFill["new"]({ad:a.E.fillStyle.toInt(true),src:a.L,ae:d.width,af:d.height,ag:d,ac:a.ac,ah:a.Z,ai:d,ab:a.ab,tolerance:Number(a.tolerance)/
100,contiguous:Boolean(a.contiguous)});b.x=b.x>d.x?b.x-d.x:0;b.y=b.y>d.y?b.y-d.y:0;a.af=a.ae.render(b);a.Z.invoke("putImageData",a.af,d.x,d.y,function(){a.L.canvas.onload=function(e){a.L.drawImage(e,0,0);a.Z.clear();a.aa=true;a.E.B()};a.L.canvas.loadImage(a.Z.canvas)})}});this.__add__(0,"c",function(a){a.Z.clearRect(0,0,a.Z.canvas.width,a.Z.canvas.height)});this.__add__(0,"n",function(a){if(a.ac){a.ac.__destroy();a.ab.__destroy();a.af.__destroy();a.ac=null;a.ab=null;a.af=null}})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Image",[c.Rect],function(){this.__add__(2,"id","image");this.__add__(0,"src","");this.__add__(0,"__new__",function(b,d){b.I=b.J=b.width=b.height=0;b.touch=false;b.E=b.parent;b.K=b.E.r.aV;b.L=b.E.o.aV;b.ag=null;if(d)b.src=d;setInterval(b.ah,100)});var a="";this.__add__(0,"ah",function(b){if(b.src!=a){a=b.src;b.ag=null;b.E.aI.onload=function(d){b.ag=d};b.E.aI.loadImage(b.src)}});this.__add__(0,
"c",function(b,d,e){c.Rect.members.__call__("c",b,d,e)});this.__add__(0,"d",function(b){b.touch=false;b.E.r.clear();b.ag&&b.width&&b.height&&b.L.drawImage(b.ag,b.I,b.J,b.width,b.height);b.width=b.height=0});this.__add__(0,"e",function(b,d,e){b.touch&&c.Rect.members.__call__("e",b,d,e)});this.__add__(0,"k",function(b,d){if(b.width&&b.height)try{d.drawImage(b.ag,b.I,b.J,b.width,b.height)}catch(e){c.Rect.members.__call__("l",b,d)}})}))})});
$Unit("","",function(){$Package("buz.drawform.tools",function(f){this.addClass(0,$buildClass("Eraser",[f.Pen],function(){this.__add__(2,"id","eraser");this.__add__(0,"__new__",function(c,a){f.Pen.members.__call__("__new__",c,"standard",a);c.fillStyle=c.E.backgroundStyle})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("Text",[c.Dummy],function(){this.__add__(2,"id","text");this.__add__(0,"fontFace","sans-serif");this.__add__(0,"fontSize",15);this.__add__(0,"bold",false);this.__add__(0,"italic",false);this.__add__(1,"text","");this.__add__(1,"at",5);this.__add__(0,"__new__",function(a,b){if(b.fontFace!=undefined)a.fontFace=b.fontFace;if(b.fontSize!=undefined)a.fontSize=Number(b.fontSize);if(b.bold!=undefined)a.bold=
Boolean(b.bold);if(b.italic!=undefined)a.italic=Boolean(b.italic);a.E=a.parent;a.K=a.E.r.aV;a.L=a.E.o.aV;a.ai=false;a.aj=false;a.ak=0;a.al({width:0});a.am=a.E.__class__.am});this.__add__(0,"ap",function(a,b,d){a.x=b;a.y=d;a.an=f.geom.Point["new"](b,d);a.width=0;a.height=0;a.ai=true;a.cursor=20;a.text="";a.ak=0});this.__add__(0,"c",function(a,b,d){if(a.ai)if(b>a.I&&d>a.J&&b<a.I+a.width&&d<a.J+a.height){a.aj=true;a.an.x=b;a.an.y=d}else{a.ao();a.ap(b,d)}else a.ap(b,d)});this.__add__(0,"a",function(){});
this.__add__(0,"b",function(a){a.ao()});this.__add__(0,"d",function(a){a.aj=false});this.__add__(0,"e",function(a,b,d){if(a.aj){var e=a.an.vectorTo(b,d);a.x+=e.x;a.y+=e.y;a.I+=e.x;a.J+=e.y;a.an.x=b;a.an.y=d;a.E.r.aY()}});this.__add__(0,"g",function(){});this.__add__(0,"h",function(a,b){if(b==a.am.SPACE)a.text+=" ";if(b==a.am.BACKSPACE)if(a.text)a.text=a.text.substr(0,a.text.length-1);a.al();return true});this.__add__(0,"i",function(a,b){a.aq(String.fromCharCode(b));return true});this.__add__(0,"aq",
function(a,b){a.text+=b;a.al()});this.__add__(0,"k",function(a,b){if(!a.E.flowArea||a.aj)a.ar(b);a.l(a.K)});this.__add__(0,"ar",function(a,b){a.ai&&a.text&&b.setFont(a.as()).setFillStyle(a.E.fillStyle).fillText(a.text,a.x,a.y)});this.__add__(0,"al",function(a){var b=a.as();a.K.setFont(b).invoke("measureText",a.text,function(d){a.width=a.ak=d.width;a.height=a.fontSize;a.I=a.x;a.J=a.y-a.fontSize})});this.__add__(0,"as",function(a){return[a.italic?"italic":"normal",a.bold?"600":"400",a.fontSize+"px",
a.fontFace].join(" ")});this.__add__(0,"l",function(a,b){if(a.ai&&!a.aj){a.E.flowArea&&a.ar(b);if(a.cursor>2){var d=a.x+a.ak+2,e=a.y-a.fontSize,g=a.fontSize+a.at;b.setFillStyle("white").setLineWidth(1).fillRect(d-1,e,1,g).setFillStyle("black").setLineWidth(1).fillRect(d,e,1,g)}if(a.cursor>0)a.cursor--;else a.cursor=10}if(a.text&&a.ak){a.width=a.ak+5;a.height=a.fontSize+a.at;c.Rect.members.__call__("l",a,b)}});this.__add__(0,"aJ",function(a){a.K.clear()});this.__add__(0,"n",function(a){a.ao()});this.__add__(0,
"ao",function(a){var b=a.E.o;b.aV.save();b.aa();a.ar(b.aV);b.aV.restore();a.ai=false;a.aJ();a.text=""})}))})});$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("TextArea",[c.Text],function(){this.__add__(2,"id","textarea");this.__add__(0,"__new__",function(a){a.au=a.av/3;a.aw=[];a.az=[]})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform.tools",function(c){this.addClass(0,$buildClass("ColorPicker",[c.Dummy],function(){this.__add__(2,"id","colorpicker");this.__add__(0,"aB",function(a,b){trace(b)});this.__add__(0,"__new__",function(a,b){a.E=a.parent;a.K=a.E.r.aV;a.L=a.E.o.aV;a.aA=false;a.touch=false;if(b!=undefined)a.aB=b;a.E.aK(null);a.I=a.J=2});this.__add__(0,"c",function(a,b,d){a.touch=true;a.I=b;a.J=d});this.__add__(0,"d",function(a,b,d){a.aC(b,d);a.touch=false});
this.__add__(0,"e",function(a,b,d){a.touch&&a.aC(b,d);a.I=b;a.J=d;a.E.r.aY()});this.__add__(0,"aC",function(a,b,d){if(!a.aA){a.aA=true;a.L.invoke("getImageData",b,d,1,1,function(e){a.aA=false;var g=e.data[0];a.aB([g>>24&255,g>>16&255,g>>8&255,g&255]);e.__destroy()})}});this.__add__(0,"l",function(a,b){b.setFillStyle("white").fillRect(a.I-2,a.J-2,4,4).setFillStyle("black").fillRect(a.I-1,a.J-1,2,2)});this.__add__(0,"k",function(a,b){a.l(b)})}))})});
$Unit("","",function(f){$Import(f,"browser","geom");$Package("buz.drawform",function(c){this.addClass(0,$buildClass("App",[],function(a){this.__add__(0,"r");this.__add__(0,"q");this.__add__(0,"container");this.__add__(0,"w",0);this.__add__(0,"z",0);this.__add__(0,["id","width","height","src","name"]);this.__add__(0,"flowArea");this.__add__(0,"touch",!!window.Touch);this.__add__(0,["strokeStyle","fillStyle","lineWidth","backgroundStyle"]);this.__add__(0,"color");this.__add__(0,["aG","aH","aI"]);this.__add__(0,
"form");this.__add__(0,"aS");this.__add__(0,"s");this.__add__(0,"o");this.__add__(0,"p");this.__add__(0,"tool");this.__add__(2,"tools",{});this.__add__(0,"t",false);this.__add__(2,"am",{BACKSPACE:8,ENTER:18,SPACE:32,LEFT:37,UP:38,RIGHT:39,DOWN:40});this.__add__(0,"aD");this.__add__(0,"__new__",function(b,d,e,g,h){b.drawform=d;w3c(b.drawform);b.width=Number(g||d.getAttribute("width")||300);b.height=Number(h||d.getAttribute("height")||150);b.id=String(e||d.getAttribute("id")||"drawform"+b.__id__);b.name=
d.getAttribute("name");b.v();b.strokeStyle=c.Color["new"]("rgba(0,0,0,1)");b.fillStyle=c.Color["new"]("rgba(0,0,0,1)");b.backgroundStyle=c.Color["new"]("rgba(255,255,255,1)");b.lineWidth=3;if(b.touch){var j=0,k=0;e=function(i){var l;switch(i.type){case "touchstart":l="c";break;case "touchend":l="d";break;case "touchmove":l="e";break}var m=i.touches[0]||{};m.button=0;m.type=i.type;if(!m.pageX)m.pageX=j;if(!m.pageY)m.pageY=k;if(b.aD.isPointWithin(m.pageX,m.pageY)){i.preventDefault();b[l](m)}j=m.pageX;
k=m.pageY};document.addEventListener("touchstart",e,false);document.addEventListener("touchmove",e,false);document.addEventListener("touchend",e,false)}else{b.drawform.addEventListener("mousedown",b.c,false);b.drawform.addEventListener("mouseup",b.d,false);b.drawform.addEventListener("mousemove",b.e,false);b.drawform.addEventListener("mouseout",b.f,false);window.addEventListener("keydown",b.h,false);window.addEventListener("keyup",b.j,false);window.addEventListener("keypress",b.i,false);window.addEventListener("mousedown",
b.C,false)}d.__appendChild=d.appendChild;d.appendChild=function(){};d.getContext=function(i){if(i!="default")return null;return b};d.toDataURL=function(i,l,m){m=typeof m=="function"?m:l;var n=b.q.canvas;return typeof qual=="number"?n.toDataURL(i,l,m):n.toDataURL(i,m)};d.__resize=function(i,l){b.width=Number(i);b.height=Number(l);b.aG.width=b.aH.width=b.aI.width=i;b.aG.height=b.aH.height=b.aI.height=l;b.aG.style.width=b.aH.style.width=b.aI.style.width=d.style.width=i+"px";b.aH.style.top="0px";b.aI.style.top=
"0px";b.aG.style.height=b.aH.style.height=b.aI.style.height=d.style.height=l+"px"};b.aG.oncanvasresize=function(){b.flowArea=null;b.clear();if(d.src){b.aG.onload=function(i){this.getContext("2d").invoke("drawImage",i,0,0,function(){b.B();b.aG.onload=null})};b.aG.loadImage(d.src)}else b.B()};b.flowArea=null;b.q=c.Layer["new"](b.aG);b.p=c.Flow["new"](b.aH);b.r=c.Glass["new"](b.aI);b.q.clear();b.o=b.q;b.s=[b.q];b.setTool("dummy");if(f.browser.isIE){b.aJ=true;b.Q=0;b.R=0;b.aI.onframe=function(){b.aJ&&
b.tool.e(b.Q,b.R);b.aJ=false}}b.setOffset()});this.__add__(0,"setTool",function(b,d,e,g,h,j,k){b.setOffset();b.aK("default");b.tool&&b.tool.n();d=a.tools[d.toLowerCase()];b.tool=d["new"].apply(d,[e,g,h,j,k])});this.__add__(2,"regTool",function(b){this.tools[b.id.toLowerCase()]=b});this.__add__(2,"__init__",function(){this.regTool(c.tools.Pen);this.regTool(c.tools.ColorPicker);this.regTool(c.tools.Dummy);this.regTool(c.tools.Ellipse);this.regTool(c.tools.Eraser);this.regTool(c.tools.Fill);this.regTool(c.tools.Image);
this.regTool(c.tools.Move);this.regTool(c.tools.Marquee);this.regTool(c.tools.Path);this.regTool(c.tools.Pencil);this.regTool(c.tools.Rect);this.regTool(c.tools.Text);this.regTool(c.tools.TextArea)});this.__add__(0,"clear",function(b){b.setTool("dummy");b.q.clear();b.r.clear();b.B()});this.__add__(0,"aK",function(b,d){b.aI.style.cursor=d||"none"});this.__add__(0,"focus",function(b){if(!b.t){document.activeElement!=document.body&&document.activeElement.blur();b.t=true;typeof b.drawform.onfocus=="function"&&
b.drawform.onfocus();b.tool.a()}});this.__add__(0,"blur",function(b){if(b.t){b.t=false;typeof b.drawform.onblur=="function"&&b.drawform.onblur();b.tool.b();b.B()}});this.__add__(0,"setStrokeStyle",function(b,d){b.strokeStyle.setColor(d)});this.__add__(0,"setFillStyle",function(b,d){b.fillStyle.setColor(d)});this.__add__(0,"setBackgroundStyle",function(b,d){b.backgroundStyle.setColor(d)});this.__add__(0,"setLineWidth",function(b,d){b.lineWidth=d});this.__add__(0,"setStrokeOpacity",function(b,d){b.strokeStyle.opacity=
Number(d)});this.__add__(0,"setFillOpacity",function(b,d){b.fillStyle.opacity=Number(d)});this.__add__(0,"aN",0);this.__add__(0,"aM",0);this.__add__(0,"aO","");this.__add__(0,"aP",0);this.__add__(0,"undo",function(b){b.aL(-1)});this.__add__(0,"redo",function(b){b.aL(+1)});this.__add__(0,"aL",function(b,d){if(typeof sessionStorage!=undefined)if(!(b.aM+d>b.aN)){var e=sessionStorage.getItem("dump"+(b.aM+d));if(e){b.aM+=d;b.q.canvas.onload=function(g){this.getContext("2d").drawImage(g,0,0);b.flowArea=
null};b.q.canvas.loadImage(e)}}});this.__add__(0,"B",function(b){typeof sessionStorage!=undefined&&b.drawform.toDataURL("image/png",function(d){if(b.aO!=d)try{for(;b.aM<b.aN;){var e=sessionStorage.getItem("dump"+b.aN);sessionStorage.removeItem("dump"+b.aN);b.aP-=e.length;b.aN--}sessionStorage.setItem("dump"+ ++b.aM,d);b.aO=d;b.aP+=d.length;b.aN++}catch(g){if(g.toString().indexOf("QUOTA_EXCEEDED_ERR"))throw b.aQ("Disk quota exceeded");}})});this.__add__(0,"c",function(b,d){b.aR();b.focus();b.o.aV.save();
b.flowArea&&b.o.aV.beginPath().rect(b.flowArea).clip();b.tool.c(b.w+d.pageX,b.z+d.pageY)&&d.preventDefault()});this.__add__(0,"aR",function(){if(document.selection&&document.selection.empty)document.selection.empty();else window.getSelection&&window.getSelection().removeAllRanges()});this.__add__(0,"C",function(b,d){b.setOffset();b.aD.isPointWithin(d.pageX,d.pageY)||b.t&&b.blur()});this.__add__(0,"d",function(b,d){setTimeout(function(){b.A=0},250);b.A+=1;var e=b.w+d.pageX,g=b.z+d.pageY;if(b.A==2)b.tool.g(e,
g)&&d.preventDefault();else b.tool.d(e,g)&&d.preventDefault();b.o.aV.restore();b.B()});this.__add__(0,"e",function(b,d){b.p.aV.dummy();b.q.aV.dummy();var e=b.w+d.pageX,g=b.z+d.pageY;if(f.browser.isIE){b.Q=e;b.R=g;b.aJ=true}else b.tool.e(e,g)&&d.preventDefault()});this.__add__(0,"f",function(b,d){b.tool.f(b.w+d.pageX,b.z+d.pageY)&&d.preventDefault()});this.__add__(0,"h",function(b,d){var e=d.keyCode;if(b.t){b.p.aV.dummy();b.q.aV.dummy();switch(e){case a.am.BACKSPACE:case a.am.ENTER:case a.am.SPACE:b.tool.h(e)&&
d.preventDefault()}}});this.__add__(0,"i",function(b,d){var e=d.charCode||d.keyCode;if(b.t)if(e)switch(e){case 0:case a.am.BACKSPACE:case a.am.ENTER:case a.am.SPACE:break;default:b.tool.i(e)&&d.preventDefault()}});this.__add__(0,"j",function(){});this.__add__(0,"setOffset",function(b){var d=b.drawform;b.w=0;b.z=0;if(d.offsetParent){do{b.w-=d.offsetLeft;b.z-=d.offsetTop}while(d=d.offsetParent)}d=b.width;var e=b.height;b.aD=f.geom.Rectangle["new"](Math.abs(b.w),Math.abs(b.z),d,e)});this.__add__(1,"v",
function(b){b.drawform.innerHTML="";b.drawform.style.width=b.width+"px";b.drawform.style.height=b.height+"px";b.drawform.style.overflow="hidden";b.drawform.style.position="relative";var d=document.createElement("canvas");d.setAttribute("id",b.id+"-q-x");d.setAttribute("width",b.width);d.setAttribute("height",b.height);d.setAttribute("frameDuration",10);d.setAttribute("style","border:0;margin:0;position:absolute;top:0px;left:0px;");var e=document.createElement("canvas");e.setAttribute("id",b.id+"-flow-x");
e.setAttribute("width",b.width);e.setAttribute("height",b.height);e.setAttribute("frameDuration",10);e.setAttribute("style","border:0;margin:0;position:absolute;top:0px;left:0px;");e.style.width=b.width+"px";e.style.height=b.height+"px";var g=document.createElement("canvas");g.setAttribute("id",b.id+"-r-x");g.setAttribute("width",b.width);g.setAttribute("height",b.height);g.setAttribute("frameDuration",10);g.setAttribute("style","border:0;margin:0;position:absolute;top:0px;left:0px;");g.style.width=
b.width+"px";g.style.height=b.height+"px";b.drawform.appendChild(d);b.drawform.appendChild(e);b.drawform.appendChild(g);b.aG=d;b.aH=e;b.aI=g;d=document.createElement("input");d.setAttribute("type","hidden");d.setAttribute("id",b.id+"-hidden-input-x");d.setAttribute("value","");b.drawform.appendChild(d);b.aS=d;b.name&&b.aT()});this.__add__(1,"aT",function(b){if(typeof b.aS.form!="undefined"){b.form=b.aS.form;b.drawform.form=b.aS.form;b.aS.name=b.name;var d;if(b.form.submit.tagName!=undefined)d=true;
w3c(b.aS,b.form);b.form.addEventListener("submit",function(e){e.preventDefault();b.aU()},false);if(!d)if(b.form.submit!==b.aU)b.form.submit=b.aU}});this.__add__(1,"aU",function(b){if(!b.u){b.u=true;b.drawform.toDataURL("image/png",function(d){b.aS.value=d;HTMLFormElement.prototype.submit.call(b.form)})}});this.__add__(1,"aQ",function(b,d){return Error(d)})}))})});
$Unit("","",function(f){$Import(f,"geom");$Package("buz.drawform",function(){this.addClass(0,$buildClass("Layer",[],function(){this.__add__(2,"id","layer");this.__add__(0,"E");this.__add__(0,"canvas");this.__add__(0,"aV");this.__add__(0,"__new__",function(c,a){c.E=c.parent;c.canvas=a;c.aV=a.getContext("2d");c.aV.setFillStyle=function(b){this.fillStyle=b.__class__&&b.__class__.className=="Color"?b.toString():b;return this};c.aV.setStrokeStyle=function(b){this.strokeStyle=b.__class__&&b.__class__.className==
"Color"?b.toString():b;return this};c.aV._tracePathBounds=false});this.__add__(0,"aa",function(c){c.parent.flowArea&&c.aV.beginPath().rect(c.parent.flowArea).clip()});this.__add__(0,"clear",function(c){var a;a=c.E.flowArea?c.E.flowArea:f.geom.Rectangle["new"](0,0,c.canvas.width,c.canvas.height);c.aV.save().setFillStyle(c.E.backgroundStyle).clearRect(a).fillRect(a).restore()})}))})});
$Unit("","",function(){$Package("buz.drawform",function(f){this.addClass(0,$buildClass("Glass",[f.Layer],function(){this.__add__(2,"id","r");this.__add__(0,"__new__",function(c,a){f.Layer.members.__call__("__new__",c,a);c.aW=[];c.canvas.onload=function(d){c.aW.push(c.aV.createPattern(d))};c.canvas.loadImage("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAALUlEQVQYlWP4jwYYGBhQMT7J////IxRgk4QrwCUJlcMtiaEAh4PxSkIU4PMqAAOGn2Gql3FAAAAAAElFTkSuQmCC","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAMklEQVQYlWP4DwUMDAwoGC6OTxIqh1sSQwEWSYQCHJIQBXgk/2PIoruJAZ/k/////wMAA4afYVpnmEkAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAMklEQVQYlYXPsQ0AMAjEQO+/tFOkIALxQaI6FwDgu334YAUL3iCgQ/tNJFQr2L4hoeoBA4afYdiStBMAAAAASUVORK5CYII=","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAMklEQVQYlYXOtw0AMAzEQO6/NN04QAlW+cdCAALmOzsftGjAHGRUX9DhDSbcNmMJuocXA4afYTYwTaEAAAAASUVORK5CYII=");var b=0;c.aX=b;setInterval(function(){c.aY();b%=3;b+=1;c.aX=b},200)});this.__add__(0,"aY",function(c){c.aV.clear();c.aV.save();c.E.tool.l(c.aV);c.aV.restore();c.aZ();
c.aV.save();c.aa();c.E.tool.k(c.aV);c.aV.restore()});this.__add__(0,"aZ",function(c){if(c.E.flowArea){var a=c.aW[c.aX];if(a){var b=c.E.flowArea.clone();b.x+=1;b.y+=1;b.width-=2;b.height-=2;var d=c.aV.fillStyle;c.aV.setFillStyle(a).fillRect(c.E.flowArea).clearRect(b).setFillStyle(d)}}});this.__add__(0,"clear",function(c){c.aV.clearRect(0,0,c.canvas.width,c.canvas.height)})}))})});
$Unit("","",function(){$Package("buz.drawform",function(f){this.addClass(0,$buildClass("Flow",[f.Layer],function(){this.__add__(2,"id","flow");this.__add__(0,"__new__",function(c,a){f.Layer.members.__call__("__new__",c,a)});this.__add__(0,"clear",function(c){c.aV.clear()})}))})});
$Unit("","",function(){$Package("buz.drawform",function(f){var c=$buildClass("RangeQueue",null,function(){this.__add__(0,"ab");this.__add__(0,"ac");this.__add__(0,"av");this.__add__(0,"__new__",function(a){a.ab=[];a.ac=0;a.av=0});this.__add__(0,"enqueue",function(a,b){if(a.av+a.ac==a.ab.length){for(var d=[],e=a.ac,g=0,h=e+a.av;e<h;e++,g++)d[g]=a.ab[e];a.ab=d;a.ac=0}a.ab[a.ac+a.av++]=b});this.__add__(0,"dequeue",function(a,b){b={};if(a.av>0){b=a.ab[a.ac];a.ab[a.ac]={};a.ac++;a.av--}return b})});f.addClass(0,
$buildClass("QueueLinearFloodFill",[],function(){this.__add__(0,["al","am","an"]);this.__add__(0,["ao","ap","aq"]);this.__add__(0,["src","ag","ac","aj","ae","af"]);this.__add__(0,["ah","ab","ak"]);this.__add__(0,["tolerance"]);this.__add__(0,["contiguous"]);this.__add__(0,["ar"]);this.__add__(0,["ad"]);this.__add__(0,"__new__",function(a,b){a.ad=b.ad||255;a.src=b.src;a.ae=b.ae||a.src.canvas.width||0;a.af=b.af||a.src.canvas.height||0;a.ag=b.ag||{x:0,y:0,width:a.ae,height:a.af};a.ac=b.ac||null;a.ah=
b.ah;a.ai=b.ai||{x:0,y:0};a.ab=b.ab||null;if(typeof b.tolerance=="number"){var d=b.tolerance*255;a.tolerance=[d,d,d]}else{d=b.tolerance;a.tolerance=[d[0]*255,d[1]*255,d[2]*255]}a.contiguous=b.contiguous});this.__add__(0,"getData",function(a){if(!a.ac)a.ac=a.src.getImageData(a.ag.x,a.ag.y,a.ag.width,a.ag.height);if(!a.ab)a.ab=a.ah.getImageData(a.ag.x,a.ag.y,a.ag.width,a.ag.height)});this.__add__(0,"render",function(a,b){var d=b.x,e=b.y,g=a.ae*e+d,h,j,k,i;a.aj=a.ac.data;a.ak=a.ab.data;h=a.aj[g];j=h>>>
24&255;k=h>>>16&255;h=h>>>8&255;a.al=j-a.tolerance[0];a.am=k-a.tolerance[1];a.an=h-a.tolerance[2];a.ao=j+a.tolerance[0];a.ap=k+a.tolerance[1];a.aq=h+a.tolerance[2];a.ar=c["new"]();if(a.contiguous)for(a.as(d,e);a.ar.av>0;){g=a.ar.dequeue();d=a.ae*(g.y+1)+g.startX;e=a.ae*(g.y-1)+g.startX;for(var l=g.y-1,m=g.y+1,n=g.startX;n<=g.endX;n++){j=a.ae*l+n;if(g.y>0){h=a.aj[j];j=h>>>24&255;k=h>>>16&255;h=h>>>8&255;i=a.ak[e]&255;!i&&j>=a.al&&j<=a.ao&&k>=a.am&&k<=a.ap&&h>=a.an&&h<=a.aq&&a.as(n,l)}j=a.ae*m+n;if(g.y<
a.af-1){h=a.aj[j];j=h>>>24&255;k=h>>>16&255;h=h>>>8&255;i=a.ak[d]&255;!i&&j>=a.al&&j<=a.ao&&k>=a.am&&k<=a.ap&&h>=a.an&&h<=a.aq&&a.as(n,m)}d++;e++}}else{d=a.aj.length;for(g=0;g<d;g+=1){h=a.aj[g];j=h>>>24&255;k=h>>>16&255;h=h>>>8&255;if(j>=a.al&&j<=a.ao&&k>=a.am&&k<=a.ap&&h>=a.an&&h<=a.aq)a.ak[g]=a.ad}}return a.ab});this.__add__(0,"as",function(a,b,d){for(var e=b,g=a.ae*d+b,h,j,k,i;;){a.ak[g]=a.ad;e--;g-=1;if(e<0)break;h=a.aj[g];j=h>>>24&255;k=h>>>16&255;h=h>>>8&255;if((i=a.ak[g]&255)||!(j>=a.al&&j<=
a.ao&&k>=a.am&&k<=a.ap&&h>=a.an&&h<=a.aq))break}e++;var l=b;for(g=a.ae*d+b;;){a.ak[g]=a.ad;l++;g+=1;if(l>=a.ae)break;h=a.aj[g];j=h>>>24&255;k=h>>>16&255;h=h>>>8&255;if((i=a.ak[g]&255)||!(j>=a.al&&j<=a.ao&&k>=a.am&&k<=a.ap&&h>=a.an&&h<=a.aq))break}l--;a.ar.enqueue({startX:e,endX:l,y:d})})}))})});
$Unit("","",function(){$Package("buz.drawform",function(){this.addClass(0,$buildClass("Color",[],function(){this.__add__(0,"at");this.__add__(0,"au");this.__add__(0,"av");this.__add__(0,"opacity");this.__add__(0,"aA");this.__add__(0,"__new__",function(f,c){f.at=0;f.au=0;f.av=0;f.opacity=0;c&&f.setColor(c)});this.__add__(0,"setColor",function(f,c){var a=c.replace(/\s+/,""),b=a.match(/rgba\((\d+),(\d+),(\d+),([\d\.]+)\)/);if(b){b.shift();b[3]=Math.round(Number(b[3])*255);f.aw.apply(f,b)}else if(b=a.match(/rgb\((\d+),(\d+),(\d+)\)/)){b.shift();
f.az.apply(f,b)}else{if(b=a.match(/^#?([\da-f]{1})([\da-f]{1})([\da-f]{1})$/i)){b[1]+=b[1];b[2]+=b[2];b[3]+=b[3]}else b=a.match(/^#?([\da-f]{2})([\da-f]{2})([\da-f]{2})([\da-f]{2})?$/i);if(b){a=parseInt(b[1],16);var d=parseInt(b[2],16),e=parseInt(b[3],16);(b=b[4]?parseInt(b[4],16):null)?f.aw(a,d,e,b):f.az(a,d,e)}else if(a.match(/^([a-z+])$/i)){f.aA=a.toLowerCase();switch(f.aA){case "white":f.az(255,255,255);break;case "black":default:f.az(0,0,0)}}else throw f.parent.aQ("Unexpected style "+c);}});
this.__add__(0,"az",function(f,c,a,b){f.at=Number(c);f.au=Number(a);f.av=Number(b);f.opacity=null});this.__add__(0,"aw",function(f,c,a,b,d){f.at=Number(c);f.au=Number(a);f.av=Number(b);f.opacity=Number(d)});this.__add__(0,"toHex",function(f,c){var a=f.at.toString(16),b=f.au.toString(16),d=f.av.toString(16),e=f.opacity.toString(16);a=["#",a,b,d];c&&a.push(e);return a.join("")});this.__add__(0,"toInt",function(f,c){return(f.at<<24)+(f.au<<16)+(f.av<<8)+(c?f.opacity==null?255:f.opacity:255)});this.__add__(0,
"__str__",function(f){return f.aA?f.aA:f.opacity==null?["rgb(",[f.at,f.au,f.av],")"].join(""):["rgba(",[f.at,f.au,f.av,f.opacity/255],")"].join("")})}))})});
